softskills_collection_name = "softskills"
hardskills_collection_name = "hardskills"
languages_collection_name = "languages"
matches_collection_name = "servermatches"
apply_scores_collection_name = "applyscores"
